language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: linux
      compiler: arm-linux-gnueabi-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabi
            - libc-dev-armel-cross
      env: CHOST=arm-linux-gnueabi
    - os: osx
      osx_image: xcode9.4
script:
- make LZMA=0 ZSTD=0 MD5=0
- make clean
- git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
- git clone -b v1.5.0 --depth=1 https://github.com/facebook/zstd.git ../zstd
- git clone --depth=1 https://github.com/sisong/libmd5.git ../libmd5
- make DIR_DIFF=0 MT=0
- make clean
- make
- # if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hdiffz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- # if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hpatchz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi
- # if [[ $TRAVIS_OS_NAME == osx ]]; then xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme unitTest -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin; fi

